baseURL = "https://vincent178.top/"
languageCode = "zh-CN"
title = "Never Too Late | vincent178 博客"
theme = "amperage"

[[menu.main]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/vincent178"
  weight = 10

[[menu.main]]
  identifier = "twitter"
  name = "Twitter"
  url = "https://twitter.com/vincent_178"
  weight = 10