baseurl = "/"
languageCode = "zh"
theme = "terminal"
paginate = 5
defaultContentLanguage="zh"

googleAnalytics="UA-167990863-1"

[markup.goldmark.renderer]
  unsafe= true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[languages]
  [languages.zh]
    languageName = "Chinese"
    title = "Curiosity"
    subtitle = "一个好奇的码农"
    owner = "vincent178"
    keywords = "golang kubernetes blog 博客"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.zh.params.logo]
      logoText = "好奇"
      logoHomeLink = "/"

    [languages.zh.menu]
      [[languages.zh.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.zh.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"

