name: Release

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v1.1.1
  publish:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install hugo
      run: |
          set -euo pipefail
          version="0.71.1"
          cd /tmp
          curl -OL https://github.com/gohugoio/hugo/releases/download/v$version/hugo_"$version"_Linux-64bit.tar.gz
          tar -xzf hugo_"$version"_Linux-64bit.tar.gz
          sudo cp hugo /usr/bin/hugo
    - name: hugo generate
      run: |
          set -euo pipefail
          git submodule init
          git submodule update
          hugo
    - name: commit files
      run: |
          set -euo pipefail
          cd public
          echo "vincent178.site" > CNAME
          git config --local user.email "vh7157@gmail.com"
          git config --local user.name "vincent178"
          git add .
          git commit -m "hugo generate" 
    - name: push changes     
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        directory: public
        repository: vincent178/vincent178.github.io
        force: true

